### ISSUE TITLE
Throws an error if i dont declare "skipheader=true"

### ISSUE THREAD

**Issue by snchtgrvr** [tresata/spark-scalding#4]
I tried running the below code, it throws cascading.taps error, saying that "was expecting 3 taps but getting 2"

And if i add "skipHeader = true" the code starts working . I can include the complete log if required
package com.tresata.spark.scalding.demo

import com.twitter.scalding.{ Args, Csv }
import com.tresata.spark.scalding.SparkJob

class DemoJob(args: Args) extends SparkJob(args) {
  override def run: Boolean = {
    val schema = List("color","name","quantity")
    Csv(args("input"), separator = "|", fields = schema ).spark.fieldsApi
      .discard('color)
      .groupBy('name){ _
        .sum[Int]('quantity)
        .size
      }
      .write(Csv(args("output"), separator = "|", writeHeader = true))

```
true
```

  }
}

**Comment by koertkuipers** [comment]
can you please post the full log, or email to me at koert at tresata dot com

i was unable to reproduce the error. the code above works for me. it gives the following  error:

Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, node04.tresata.com): java.lang.NumberFormatException: For input string: "quantity"

this error is expected, since the data file includes headers, which are now interpreted as data, and "quantity" cannot be converted to a number.

**Comment by snchtgrvr** [comment]
I think there is some error in the data i was passing to the class. please close the issue.
